# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(694, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sel_model_bt = QtWidgets.QPushButton(self.centralwidget)
        self.sel_model_bt.setGeometry(QtCore.QRect(560, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.sel_model_bt.setFont(font)
        self.sel_model_bt.setObjectName("sel_model_bt")
        self.sel_vdo_bt = QtWidgets.QPushButton(self.centralwidget)
        self.sel_vdo_bt.setGeometry(QtCore.QRect(560, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sel_vdo_bt.setFont(font)
        self.sel_vdo_bt.setObjectName("sel_vdo_bt")
        self.model_path = QtWidgets.QTextEdit(self.centralwidget)
        self.model_path.setGeometry(QtCore.QRect(10, 10, 541, 31))
        self.model_path.setObjectName("model_path")
        self.vdo_path = QtWidgets.QTextEdit(self.centralwidget)
        self.vdo_path.setGeometry(QtCore.QRect(10, 50, 541, 31))
        self.vdo_path.setObjectName("vdo_path")
        self.video_display = QtWidgets.QLabel(self.centralwidget)
        self.video_display.setGeometry(QtCore.QRect(10, 100, 671, 381))
        self.video_display.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.video_display.setText("")
        self.video_display.setObjectName("video_display")
        self.start_bt = QtWidgets.QPushButton(self.centralwidget)
        self.start_bt.setGeometry(QtCore.QRect(10, 490, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.start_bt.setFont(font)
        self.start_bt.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.start_bt.setObjectName("start_bt")
        self.ent_label = QtWidgets.QLabel(self.centralwidget)
        self.ent_label.setGeometry(QtCore.QRect(160, 490, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ent_label.setFont(font)
        self.ent_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ent_label.setObjectName("ent_label")
        self.ext_label = QtWidgets.QLabel(self.centralwidget)
        self.ext_label.setGeometry(QtCore.QRect(390, 490, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ext_label.setFont(font)
        self.ext_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ext_label.setObjectName("ext_label")
        self.lcd_ent = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_ent.setGeometry(QtCore.QRect(263, 492, 91, 51))
        self.lcd_ent.setObjectName("lcd_ent")
        self.lcd_ext = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_ext.setGeometry(QtCore.QRect(480, 490, 91, 51))
        self.lcd_ext.setObjectName("lcd_ext")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sel_model_bt.setText(_translate("MainWindow", "Select Model"))
        self.sel_vdo_bt.setText(_translate("MainWindow", "Select Video"))
        self.start_bt.setText(_translate("MainWindow", "Start"))
        self.ent_label.setText(_translate("MainWindow", "Entrance"))
        self.ext_label.setText(_translate("MainWindow", "Exist"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
